### ISSUE TITLE
07.02.2022

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Gunka999/-PragmatechFrontEndProject#1]
Salam, Günel.🙂

Reponu hər gün update etməyə çalışın. CSS və JavaScript fayllarını uyğun olaraq "css" və "js" adlı qovluğa əlavə etsəniz daha yaxşı olar. Repoya əlavə olunan bütün faylların içi boşdur, içini tapşırıqlar ilə doldurmağa çalışın. 

Uğurlar!

**Comment by Gunka999** [comment]
Salam Nergiz. Duzu elave ede bilmirem problem yaranir. Papkani test etmek ucun yaratmisdim. Elaveleri indi ede bilmirem
